In [2]:
input("How are you doing today? (good or bad): ")

How are you doing today? (good or bad):  good


'good'

In [12]:
num = float(input("Enter a number: "))
if num > 0:
   print("Positive number")
elif num == 0:
   print("Zero")
else:
   print("Negative number")

Enter a number:  -2


Negative number


In [46]:
num = int(input("Enter a number: "))
if num > 0:
   print("Positive number")
elif num == 0:
   print("Zero")
else:
   print("Negative number")

Enter a number:  1


Positive number


In [88]:
num = int(input("Enter a number: "))
if num > 0:
   print("Positive number")
elif num == 0:
   print("Zero")
else:
   print("Negative number")

Enter a number:  0


Zero


In [20]:
l4 = [5,7,22,97,45,65,66,78,34,56,74,32,33,23]
odd_numbers = []
for num in l4:
    if num % 2 != 0:
        odd_numbers.append(num)
print("Odd numbers (loop):", odd_numbers)

Odd numbers (loop): [5, 7, 97, 45, 65, 33, 23]


In [22]:
odd_numbers = list(filter(lambda x: x % 2 != 0, l4))
print("Odd numbers (lambda with filter):", odd_numbers)

Odd numbers (lambda with filter): [5, 7, 97, 45, 65, 33, 23]


In [24]:
input ("How are you doing today? (Good or Bad)")


How are you doing today? (Good or Bad) Good


'Good'

In [36]:
Chat = input("How are you doing today? (Good or Bad): ")

if Chat == 'Good':
    print("Great to hear")
else:
    print("Oops")

How are you doing today? (Good or Bad):  Good


Great to hear


In [40]:
Chat = input("Could it because of the auspicious weather? (Yes or No): ")

if Chat == 'Yes':
    print("I guessed as much")
else:
    print("Oh can you share why then")

Could it because of the auspicious weather? (Yes or No):  Yes


I guessed as much


In [42]:
is_raining = True

if is_raining:
    print("Take an umbrella.")
else:
    print("Enjoy the sunshine!")

Take an umbrella.


In [44]:
Chat = input("Is it raining? (Yes or No): ")

is_it_raining = True

if True:
    print("Take an umbrella.")
else:
    print("Enjoy the sunshine!")

Is it raining? (Yes or No):  Yes


Take an umbrella.


In [68]:
a = float( input ("enter a number: "))
if a < 0: print ("negative number")
else: print ("positive number")

enter a number:  10.1


positive number


In [70]:
num = 1

while num <= 5:
    print(num)
    num += 1

1
2
3
4
5


In [72]:
num = 1

while num <= 5:
    print(num)
    num = num + 1

1
2
3
4
5


In [ ]:
num = float(input("Enter a number: "))

if num < 0:
    print("Negative number")
else:
    print("Positive number")


In [74]:
secret_number = 7  # The number to guess
guess = None       # Start with no guess

while guess != secret_number:
    guess = int(input("Guess a number between 1 and 10: "))
    
    if guess < secret_number:
        print("Too low!")
    elif guess > secret_number:
        print("Too high!")

print("🎉 Correct! You guessed the number.")


Guess a number between 1 and 10:  2


Too low!


Guess a number between 1 and 10:  1


Too low!


Guess a number between 1 and 10:  8


Too high!


Guess a number between 1 and 10:  5


Too low!


Guess a number between 1 and 10:  7


🎉 Correct! You guessed the number.


In [76]:
secret_number = 7  # The number to guess
guess = None       # Start with no guess

while guess != secret_number:
    guess = int(input("Guess a number between 1 and 10: "))
    
    if guess < secret_number:
        print("Too low!")
    elif guess > secret_number:
        print("Too high!")

else print("🎉 Correct! You guessed the number.")

Guess a number between 1 and 10:  3


Too low!


Guess a number between 1 and 10:  7


🎉 Correct! You guessed the number.


In [80]:
secret_number = 7  # The number to guess
guess = None       # Start with no guess

while guess != secret_number:
    guess = int(input("Guess a number between 1 and 10: "))
    
    if guess < secret_number:
        print("Too low!")
    elif guess > secret_number:
        print("Too high!")

else: print("🎉 Correct! You guessed the number.")

Guess a number between 1 and 10:  5


Too low!


Guess a number between 1 and 10:  4


Too low!


Guess a number between 1 and 10:  9


Too high!


Guess a number between 1 and 10:  7


🎉 Correct! You guessed the number.


In [82]:
user_name = input("What is your name? ")
print("Hello,", user_name)


What is your name?  Oluwatosin


Hello, Oluwatosin


In [84]:
num = 7
if num % 2 == 0:
    print("Even")
else:
    print("Odd")

Odd


In [86]:
age = 18
print(age == 18)  # Output: True


True


In [92]:
color = "red"
print(color == "blue")


False


In [94]:
color = "red"
print(color != "blue")  # Output: True


True


In [123]:
numbers = [10, 15, 22, 33, 42, 55, 60]
odd= []

for num in numbers:
 if num % 2 != 0:
  odd.append(num)

print(odd)

[15, 33, 55]


In [153]:
numbers = [10, 15, 22, 33, 42, 55, 60]
odd = []

for num in numbers:
    if num % 2 != 0:
        odd.append(num)

print(odd)


[15, 33, 55]


In [145]:
numbers = [1, 2, 3, 4, 5]
squares = []
for num in numbers:
    if num > 2:
        squares.append(num * num)
print(squares)

[9, 16, 25]


In [147]:
names = ["Alice", "Bob", "Charlie"]
for name in names:
    if name != "Bob":
        print("Hello", name)


Hello Alice
Hello Charlie


In [155]:
user_name = input("What is your name? ")
print("Hello,", user_name)

What is your name?  Patrick


Hello, Patrick


In [1]:
l2 = range(1,10)
l2

range(1, 10)

In [13]:
    for i in l2:
        print(i)

1
2
3
4
5
6
7
8
9


In [15]:
l_even = [i for i in l2 if i%2==0]
l_even
    

[2, 4, 6, 8]

In [17]:
l4= [5,7,22,97,45,65,66,78,34,56,74,32,33,23]
l4_odd= [i for i in l4 if i%2 !=0]
l4_odd

[5, 7, 97, 45, 65, 33, 23]

In [23]:
list(filter(lambda i: i%2==0, l4))

[22, 66, 78, 34, 56, 74, 32]

In [25]:
list(filter(lambda i: i%2==0, l2))

[2, 4, 6, 8]

In [33]:
list(map(lambda i: i*10, l4))

[50, 70, 220, 970, 450, 650, 660, 780, 340, 560, 740, 320, 330, 230]

In [35]:
import numpy as np


In [39]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [41]:
a5=np.array([[1,2], [3,4]])

In [43]:
a5

array([[1, 2],
       [3, 4]])

In [47]:
a5.ndim

2

In [51]:
a5.shape

(2, 2)

In [53]:
a5.size

4

In [61]:
a5.transpose

<function ndarray.transpose>

In [57]:
a5

array([[1, 2],
       [3, 4]])

In [63]:
a5 = np.array([[1, 2],
               [3, 4]])

transposed = a5.T
print(transposed)

[[1 3]
 [2 4]]


In [71]:
a5[0,0]=5

In [73]:
a5

array([[5, 2],
       [3, 4]])

In [75]:
a5[0,0:]=5

In [77]:
a5

array([[5, 5],
       [3, 4]])